### PR TITLE
feat(npm scripts): simplify run scripts

### PR DESCRIPTION
**Pull request by elmariofredo**
- replace serve-static and server.js with node-static
- remove progress from webpack to ensure clean url in cmd output
- add webpack build before starting static server
- update Readme.md accordingly

### CODE REVIEW

**Comment by elmariofredo** [comment]
sorry guys don't want to be picky :)

Quite frankly not sure what is purpose of serving static files here, but it would not work under Windows as you would have to normalize path.

Also as a side note I would not suggest to install npm packages to global, it's not really best option as you will get easily between versions, breaking changes and your projects.

**Comment by elmariofredo** [comment]
extra points for reference to Rick and Morty :scream:

**Comment by kronik3r** [comment]
Thanks man for your help we really appreciate it :+1: :facepunch: hope to see you tomorrow.

PS: I wanted to push the Rick and Morty thing very far :D but I was afraid of the lack of fans, but you give me hope :D.

**Comment by elmariofredo** [comment]
Sure thing :) see you there

**Pull request merged**
